name: Test (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
    - name: Install
      run: sudo make install-all-linux
    - name: Run tests
      run: make test
